# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ""
    org_name: "Fail. Learn. Repeat."
    description: "Fuckups and revelations in tech and life"
    twitter: "fxlrnrpt"
  analytics:
    google_analytics: "G-4B4QT8F1PR"
    baidu_tongji: ""
    plausible: ""
    fathom: ""
    pirsch: ""
  verification:
    google: ""
    baidu: ""

# Site header
header:
  navbar:
    enable: true
    show_search: true
    show_theme_chooser: true
    align: "center"

# Site footer
footer:
  copyright:
    notice: "© {year} Me. This work is licensed under {license}"
    license:
      enable: true
      allow_derivatives: true
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: "Jan 2, 2006"
  time_format: "3:04 PM"

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: "https://github.com/fxlrnrpt/blog.faillearnrepeat.net"
    content_dir: content
    branch: main
